#!/bin/bash
#my alias
stty -ixon # disable ctrl-s in vim
alias ..='cd ..;ls'
alias js='node'
alias nd='node-debug'
alias install='sudo apt-get install'
alias bi='bundle install'
alias be='bundle exec'
alias bp='vim ~/.bashrc'
alias vp='vim ~/.vimrc'
alias pp='vim ~/.pryrc'
alias tp='vim ~/.tern-project'
alias aa='cd ~/Documents/appacademy/'
alias l='ls -laH'
alias gs='git status'
alias gl='git log'
alias gf='git diff'
alias gc='git clone'
alias gh='git push heroku'
alias hm='heroku run rake db:migrate'
alias hs='heroku run rake db:seed'
alias hr='heroku run rake db:reset'
alias sd='rake db:seed:dump APPEAD=true'
alias bes='bundle exec rspec'
alias besf='bundle exec rspec --fail-fast'
alias f='find -name'
alias rbp='source ~/.bashrc'
alias v='vim'
alias rm='rm -rf'
alias open='xdg-open'
alias rs='vim ~/.vim/bundle/vim-snippets/UltiSnips/ruby.snippets'
alias jss='vim ~/.vim/bundle/vim-snippets/UltiSnips/javascript.snippets'
alias snippets='cd ~/.vim/bundle/vim-snippets/UltiSnips/'
alias n='nautilus .'
alias cp='cp -r'
alias b='cd -'
alias cl='clear'
alias h='history'
alias j='jobs -l'
alias fping='ping -c 100 -s.2'
alias rs='open ~/Documents/OSBuddy.jar'
alias ping='ping -c 5'
alias pingt='ping'
alias top='atop'
alias p='cd ~/.vim/bundle'
#rails development
alias routes='rake routes'
alias migrate='rake db:migrate'
alias create='rake db:create'
alias model='rails g model'
alias controller='rails g controller'
alias killkodi='pkill -9 kodi.bin'
alias destroy='rails destroy'
alias mailer='rails g mailer'
alias s='rails s'
alias rc='rails c'
alias brake='bundle exec rake db:migrate db:test:load'
alias railspid='lsof -wni tcp:3000'
#update node
alias unode='curl https://raw.githubusercontent.com/isaacs/nave/master/nave.sh | sudo bash -s -- usemain latest'
#allows vi commands at terminal
#set -o vi 
alias aws1='ssh -i ~/Documents/Bellenista/AWS/Key\ Pairs/bellenista-key-pair-westcali.pem deploy@ec2-54-153-42-235.us-west-1.compute.amazonaws.com'
alias aws3='ssh -i ~/Documents/Bellenista/AWS/Key\ Pairs/bellenista-key-pair-westcali.pem deploy@ec2-54-183-56-1.us-west-1.compute.amazonaws.com'
alias aws='ssh -i ~/Documents/Bellenista/AWS/Key\ Pairs/bellenista-key-pair-westcali.pem deploy@ec2-52-53-254-165.us-west-1.compute.amazonaws.com'
alias pihole='ssh 192.168.1.50'
alias raspi='ssh 192.168.1.51'
alias update='sudo apt-get -y update;sudo apt-get -y upgrade'

bind '"\e[5": history-search-backward'
bind '"\e[6": history-search-forward'
bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'
#scripts

pop () {
  cd ~/Documents/popcorntime/popcorn-desktop
  gulp run
}

uninstall () {
  sudo apt-get remove $1
}

belle () {
  cd ~/Documents/Bellenista/BelleProject/BelleApp
  rails s
}
mkcd () {
  case "$1" in
    */..|*/../) cd -- "$1";; # that doesn't make any sense unless the directory already exists
    /*/../*) (cd "${1%/../*}/.." && mkdir -p "./${1##*/../}") && cd -- "$1";;
    /*) mkdir -p "$1" && cd "$1";;
    */../*) (cd "./${1%/../*}/.." && mkdir -p "./${1##*/../}") && cd "./$1";;
    ../*) (cd .. && mkdir -p "${1#.}") && cd "$1";;
    *) mkdir -p "./$1" && cd "./$1";;
  esac
}

gg () {
  git add -A
  git commit -m "$1"
  git push
  git log
}

#alias wp='webpack --progress --colors --watch ./root.js bundle.js'

wp () {
  webpack --progress --colors --watch ${1:-root.js} bundle.js
}

aae () {
    aa
    mkcd $1/exercises
}

guards () {
    cp ~/Documents/appacademy/gems/Gemfile .
    cp ~/Documents/appacademy/gems/Guardfile .
    bundle install --without rails railtest
    bundle exec guard
}

guardr () {
    cp ~/Documents/appacademy/gems/Gemfile .
    cp ~/Documents/appacademy/gems/Guardfile .
    bundle install --without sql
    bundle exec guard
}


gu () {
  cd
  git add -u
  git commit -m "$1"
  git push
  git log
}

react () {
  react new $1
  cd $1
  cp ~/Documents/appacademy/React/.gitignore .
}

c () {
  cd $1
  ls
}
