#!/bin/bash
#my alias
stty -ixon # disable ctrl-s in vim
alias ..='cd ..;ls'
alias js='node'
alias nd='node-debug'
alias bi='bundle install'
alias be='bundle exec'
alias bp='vim ~/.aliases'
alias vp='vim ~/.vimrc'
alias tp='v ~/.tmux.conf'
alias l='ls -laH'
alias gs='git status'
alias gl='git log'
alias gd='git diff'
alias gc='git clone'
alias bes='bundle exec rspec'
alias besf='bundle exec rspec --fail-fast'
alias f='find -name'
alias rbp='source ~/.bashrc'
alias v='vim'
alias rm='rm -rf'
alias cp='cp -r'
alias b='cd -'
alias cl='clear'
alias h='history'
alias j='jobs -l'
alias top='atop'
alias p='cd ~/.vim/bundle'
#rails development
alias killkodi='pkill -9 kodi.bin'
alias s='rails s'
alias rc='rails c'
alias brake='bundle exec rake db:migrate db:test:load'
alias railspid='lsof -wni tcp:3000'
#update node
#allows vi commands at terminal
#set -o vi 
alias aws1='ssh -i ~/.ssh/AWS/Key\ Pairs/bellenista-key-pair-westcali.pem deploy@ec2-54-153-42-235.us-west-1.compute.amazonaws.com'
alias aws3='ssh -i ~/.ssh/AWS/Key\ Pairs/bellenista-key-pair-westcali.pem deploy@ec2-54-183-56-1.us-west-1.compute.amazonaws.com'
alias aws='ssh -i ~/.ssh/AWS/Key\ Pairs/bellenista-key-pair-westcali.pem deploy@ec2-52-53-254-165.us-west-1.compute.amazonaws.com'
alias pihole='ssh 192.168.1.50'
alias raspi='ssh 192.168.1.51'
alias update='softwareupdate -iva'

bind '"\e[5": history-search-backward'
bind '"\e[6": history-search-forward'
bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'
#scripts

belle () {
  cd ~/Documents/Bellenista/BelleProject/BelleApp
  rails s
}
mkcd () {
  case "$1" in
    */..|*/../) cd -- "$1";; # that doesn't make any sense unless the directory already exists
    /*/../*) (cd "${1%/../*}/.." && mkdir -p "./${1##*/../}") && cd -- "$1";;
    /*) mkdir -p "$1" && cd "$1";;
    */../*) (cd "./${1%/../*}/.." && mkdir -p "./${1##*/../}") && cd "./$1";;
    ../*) (cd .. && mkdir -p "${1#.}") && cd "$1";;
    *) mkdir -p "./$1" && cd "./$1";;
  esac
}

gg () {
  git add -A
  git commit -m "$1"
  git push
  git log
}

#alias wp='webpack --progress --colors --watch ./root.js bundle.js'

wp () {
  webpack --progress --colors --watch ${1:-root.js} bundle.js
}

